Error - command not supported:
  *PREPRINT
Error - command not supported:
  *USER MATERIAL
Error - command not supported:
  *USER OUTPUT VARIABLES
Error - command not supported:
  *DAMAGE INITIATION
Error - command not supported:
  *DAMAGE EVOLUTION
Error - command not supported:
  *STEP
Error - command not supported:
  *SOLUTION TECHNIQUE
Error - NSET SET-29 referred by BOUNDARY is not defined
Error - NSET SET-30 referred by BOUNDARY is not defined
Error - NSET SET-30 referred by BOUNDARY is not defined
Error - NSET SET-30 referred by BOUNDARY is not defined
Error - NSET SET-30 referred by BOUNDARY is not defined
Error - NSET SET-30 referred by BOUNDARY is not defined
Error - NSET SET-30 referred by BOUNDARY is not defined
Error - command not supported:
  *RESTART
Error - command not supported:
  *END STEP
Message 0
